
title: OCTA-RV dataset
page-top-title: OCTA-RV
top-section-bg-text: Computer Science
home-subtitle: Datatset Description
copyright-text: '&copy; Units: Qufu Normal University Computer College. Email: mafei0603@163.com.'
