
title: OCTA-RV dataset
page-top-title: OCTA-RV
top-section-bg-text: GLDENet:A Global-Local Dual-branch Encoder Network based on Attention Voting in OCT-Angiography Vessels Segmentation and New Dataset.
home-subtitle: Datatset Description
copyright-text: '&copy; Units: Qufu Normal University Computer College. Email: mafei0603@163.com.'
